{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/Users/cm772/Documents/Dev/tptp-features\n"
     ]
    }
   ],
   "source": [
    "cd .."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "SINGLE_TIMEOUT = 60*5\n",
    "TOTAL_TIMEOUT = 3600*8"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "from tptp_features.strategic_features import get_features"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/GEO/GEO510+1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/GEO/GEO510+1.p\n",
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/GEO/GEO511+1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/GEO/GEO511+1.p\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV106_1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV092-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV100-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV094+1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV088=1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV090-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV125_1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV125-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/HWV/HWV126_1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/HWV/HWV126_1.p\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV124+1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/SYN/SYN853-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/HWV/HWV094_1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/HWV/HWV094_1.p\n",
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/HWV/HWV127+1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/HWV/HWV127+1.p\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV106+1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV134=1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV096-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV088_1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/SWW/SWW678=1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/SWW/SWW678=1.p\n",
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/HWV/HWV125=1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/HWV/HWV125=1.p\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV127=1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/HWV/HWV123-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/HWV/HWV123-1.p\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV131-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/HWV/HWV127_1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/HWV/HWV127_1.p\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV128-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/SWW/SWW677=1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/SWW/SWW677=1.p\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/LCL/LCL680+1.020.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV132-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV096_1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV096=1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/SYN/SYN854-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/GEO/GEO538+1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/GEO/GEO538+1.p\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV126=1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV094-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV088-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV134_1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV126-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/GEO/GEO408^1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/GEO/GEO408^1.p\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV100+1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV092+1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/HWV/HWV124-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/HWV/HWV124-1.p\n",
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/GEO/GEO539+1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/GEO/GEO539+1.p\n",
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/SWW/SWW676=1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/SWW/SWW676=1.p\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV133-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV133+1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/SWW/SWW679=1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/SWW/SWW679=1.p\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/SYN/SYN842-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV126+1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/HWV/HWV106=1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/HWV/HWV106=1.p\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV123+1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV106-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV134+1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV128=1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/HWV/HWV092_1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/HWV/HWV092_1.p\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV129-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV092=1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV132=1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV127-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV094=1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV098-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV123=1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV128_1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV100_1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV130-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/SYN/SYN855-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/HWV/HWV133_1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/HWV/HWV133_1.p\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV134-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/HWV/HWV133=1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/HWV/HWV133=1.p\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV128+1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/SYN/SYN852-1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV123_1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Future returned an exception: ../tptp-parser/Problems/HWV/HWV124_1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 136, in get_problem_features_rq\n",
      "    raise ProblemFeaturesFailedException(filename, timeout, e)\n",
      "tptp_features.strategic_features.ProblemFeaturesFailedException: ../tptp-parser/Problems/HWV/HWV124_1.p\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV096+1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV125+1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV132+1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV088+1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV132_1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n",
      "ERROR:root:Timed-out: ../tptp-parser/Problems/HWV/HWV100=1.p\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 160, in get_features\n",
      "    s = future.result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/Users/cm772/Documents/Dev/tptp-features/tptp_features/strategic_features.py\", line 143, in get_problem_features_rq\n",
      "    raise ProblemFeaturesTimeoutException(filename, timeout, \"Waited for rq, but failed\")\n",
      "tptp_features.strategic_features.ProblemFeaturesTimeoutException: Waited for rq, but failed\n"
     ]
    }
   ],
   "source": [
    "data, incomplete = get_features(\"../tptp-parser/\", SINGLE_TIMEOUT, TOTAL_TIMEOUT)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "incomplete = pd.Series([(p.parent.name, p.name) for p in incomplete])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "count                    79\n",
       "unique                   79\n",
       "top       (GEO, GEO538+1.p)\n",
       "freq                      1\n",
       "dtype: object"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "incomplete.describe()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3331: PerformanceWarning: \n",
      "your performance may suffer as PyTables will pickle object types that it cannot\n",
      "map directly to c-types [inferred_type->mixed,key->values] [items->None]\n",
      "\n",
      "  exec(code_obj, self.user_global_ns, self.user_ns)\n"
     ]
    }
   ],
   "source": [
    "store = pd.HDFStore('problem_features.h5')\n",
    "store['features'] = data\n",
    "store['incomplete'] = incomplete\n",
    "store['timeouts'] = pd.Series(dict(single=SINGLE_TIMEOUT, total=TOTAL_TIMEOUT))\n",
    "store.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0     (GEO, GEO511+1.p)\n",
       "1     (HWV, HWV088-1.p)\n",
       "2     (HWV, HWV127+1.p)\n",
       "3     (SYN, SYN852-1.p)\n",
       "4     (HWV, HWV128_1.p)\n",
       "            ...        \n",
       "74    (HWV, HWV106=1.p)\n",
       "75    (SYN, SYN853-1.p)\n",
       "76    (HWV, HWV088=1.p)\n",
       "77    (HWV, HWV128-1.p)\n",
       "78    (SWW, SWW676=1.p)\n",
       "Length: 79, dtype: object"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "incomplete"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
